# Document:
# http://simiki.org/docs/configuration.html

url: 
title: 
keywords: 
description: 
author: 

deploy:
    type: 'git'
    remote: https://github.com/siwting/siwting.github.io.git
    branch: 'master'